### ISSUE TITLE
Create player object

### ISSUE THREAD

**Issue by rockmanvnx6** [nugyn/SEF-PRAC01-G4#6]
**Players need to have the following**
Params:
- [x] Player name ( For login system )
- [x] Is Alive (Boolean)
- [x] Position x - according to the grid
- [x] Position y - according to the grid
<hr />
Function:

- [x] Move Left
- [x] Move Right
- [x] Move Top
- [x] Move Bottom

**Comment by rockmanvnx6** [comment]
asdasd

**Comment by nugyn** [comment]
Refer use cases and UML for more info

**Comment by rockmanvnx6** [comment]
#10
